# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [Rivarkurd, Ruozitaw]
patreon: # Replace with a single Patreon Rivarkurd
open_collective: # Replace with a single Open Collective Rivarkurd
ko_fi: # Replace with a single Ko-fi Rivarkurd
tidelift: # Replace with a single Tidelift platform-name/Rivarkurd e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay Rivarkurd
issuehunt: # Replace with a single IssueHunt Rivarkurd
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar Rivarkurd
buy_me_a_coffee: # Replace with a single Buy Me a Coffee Rivarkurd
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
